name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        run: |
          CURRENT_VERSION=$(grep "version =" build.gradle.kts | cut -d' ' -f3 | tr -d "'")
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{ $NF+=1; print }' OFS=".") 
          sed -i "s/version = \"$CURRENT_VERSION\"/version = \"$NEW_VERSION\"/" build.gradle.kts
          git config user.name "github-actions[bot]"
          git config user.email "<>"
          git add build.gradle.kts
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git push
      
      - name: Checkout with updated version 
        uses: actions/checkout@v3
      
      - name: Build and push Docker image
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
          UPDATED_VERSION=$(grep "version =" build.gradle.kts | cut -d' ' -f3 | tr -d "'")

          docker build -t jamoos/graal:latest \
                       -t jamoos/graal:$UPDATED_VERSION .
          docker push jamoos/graal:latest
          docker push jamoos/graal:$UPDATED_VERSION
